global:
  namespace: k8s-exam-ckad
  examType: ckad
  difficulty: beginner
exam:
  type: ckad
  difficulty: beginner
  timeLimit: 2h
  passingScore: 67
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m
nodeSelector:
tolerations:
affinity:
