apiVersion: v1
kind: Pod
metadata:
  name: labeled-pod
  namespace: venus
  labels:
    app: labeled-pod
    exam-resource: "true"
    type: "prerequisite"
spec:
  containers:
  - name: app
    image: nginx:1.20-alpine
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"