apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: k8s-exam-ckad
  labels:
    app: sample-app
    exam-resource: "true"
spec:
  selector:
    app: sample-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP