apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-neptune
  namespace: neptune
  labels:
    app: sample-app-neptune
    exam-resource: "true"
    planet: neptune
spec:
  containers:
  - name: nginx
    image: nginx:1.20
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"