apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-venus
  namespace: venus
  labels:
    exam-resource: "true"
    planet: venus
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQ=  # password