apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
  namespace: k8s-exam-ckad
  labels:
    exam-resource: "true"
data:
  app.properties: |
    debug=false
    database.host=localhost
    database.port=5432
  config.yaml: |
    server:
      port: 8080
      timeout: 30s