apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-uranus
  namespace: uranus
  labels:
    exam-resource: "true"
    planet: uranus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi