apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-mercury
  namespace: mercury
  labels:
    exam-resource: "true"
    planet: mercury
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQ=  # password