apiVersion: v1
kind: Service
metadata:
  name: sample-service-mars
  namespace: mars
  labels:
    app: sample-app-mars
    exam-resource: "true"
    planet: mars
spec:
  selector:
    app: sample-app-mars
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP