apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc
  namespace: k8s-exam-ckad
  labels:
    exam-resource: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi