apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: k8s-exam-ckad
  labels:
    app: sample-app
    exam-resource: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"