apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-jupiter
  namespace: jupiter
  labels:
    exam-resource: "true"
    planet: jupiter
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQ=  # password